In [4]:
import pandas as pd

# Define the file path
file_path = 'variants_new_vcf.csv'  # Update the path as necessary if the file is located elsewhere

# Read the file into a DataFrame, assuming it is tab-separated
df = pd.read_csv(file_path)

# Display the first few rows of the DataFrame to understand its structure
df

,CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO,FORMAT,col_1,...,col_1499,col_1500,col_1501,col_1502,col_1503,col_1504,col_1505,col_1506,col_1507,col_1508
0,4,1807361,.,A,C,.,.,PR,GT,1/0,...,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0
1,4,1807362,.,C,A,.,.,PR,GT,1/0,...,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0
2,4,1807364,.,T,A,.,.,PR,GT,1/0,...,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0
3,7,138391456,.,G,A,.,.,PR,GT,0/0,...,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0
4,7,138391455,.,T,A,.,.,PR,GT,0/0,...,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4519,11,17167416,.,T,A,.,.,PR,GT,0/0,...,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,1/1,0/0
4520,11,17167415,.,G,A,.,.,PR,GT,0/0,...,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,1/1,0/0
4521,5,74055200,.,T,A,.,.,PR,GT,0/0,...,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,1/1
4522,5,74055199,.,A,C,.,.,PR,GT,0/0,...,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,1/1
4523,5,74055198,.,G,C,.,.,PR,GT,0/0,...,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,1/1

In [75]:
import pandas as pd

def new_variants(v, n, m, i):
    """
    Extract rows and columns from 'variants_new_vcf.csv' and add extra columns efficiently.

    Args:
        v (int): number of rows per disease block to select (1-3)
        n (int): number of top diseases (first 5+n columns)
        m (int): number of bottom diseases (last m columns)
        i (int): number of extra columns with all values set to "0/0"

    Returns:
        pd.DataFrame: extracted dataset with extra columns
    """
    # Load dataset
    df = pd.read_csv("variants_new_vcf.csv")

    # Ensure n and m are within reasonable limits
    n = min(n, 814)
    m = min(m, 694)
    
    # Each disease has 3 rows
    disease_rows = 3
    total_diseases = len(df) // disease_rows
    
    # -------------------------
    # Step 1: select rows
    # -------------------------
    top_rows = [d * disease_rows + r for d in range(n) for r in range(v)]
    bottom_rows = [d * disease_rows + r for d in range(total_diseases - m, total_diseases) for r in range(v)]
    
    selected_rows = top_rows + bottom_rows
    df_rows_selected = df.loc[selected_rows].reset_index(drop=True)
    
    # -------------------------
    # Step 2: select columns
    # -------------------------
    df_first = df_rows_selected.iloc[:, :9+n].copy()  # first 9+n columns
    df_last = df_rows_selected.iloc[:, -m:].copy()    # last m columns
    
    # Combine first and last columns
    df_final = pd.concat([df_first, df_last], axis=1)
    
    # -------------------------
    # Step 3: add i extra columns with "0/0" efficiently
    # -------------------------
    if i > 0:
        new_cols = pd.DataFrame("0/0", index=df_final.index, columns=[f'new_col_{j+1}' for j in range(i)])
        df_final = pd.concat([df_final, new_cols], axis=1)
    
    # -------------------------
    # Step 4: save results
    # -------------------------
    df_final.to_csv('new_variants.txt', sep='\t', index=False, header=False)
    
    # Extract CHROM and POS columns
    chrom_pos_columns = df_final[['CHROM', 'POS']]
    chrom_pos_columns.to_csv("new_chrom_pos.txt", index=False, header=False, sep='\t')
    
    return df_final

In [84]:
new_variants(1, 814, 694, 492)

,CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO,FORMAT,col_1,...,new_col_483,new_col_484,new_col_485,new_col_486,new_col_487,new_col_488,new_col_489,new_col_490,new_col_491,new_col_492
0,4,1807361,.,A,C,.,.,PR,GT,1/0,...,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0
1,7,138391456,.,G,A,.,.,PR,GT,0/0,...,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0
2,1,154574736,.,T,A,.,.,PR,GT,0/0,...,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0
3,2,163128876,.,G,A,.,.,PR,GT,0/0,...,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0
4,16,1505769,.,G,A,.,.,PR,GT,0/0,...,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1503,15,52425585,.,A,C,.,.,PR,GT,0/0,...,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0
1504,17,8076856,.,G,A,.,.,PR,GT,0/0,...,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0
1505,1,150990372,.,C,A,.,.,PR,GT,0/0,...,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0
1506,11,17167417,.,A,C,.,.,PR,GT,0/0,...,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0
1507,5,74055200,.,T,A,.,.,PR,GT,0/0,...,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0